FROM node:20-alpine AS base
WORKDIR /app
COPY frontend/package.json ./package.json
RUN npm install
COPY frontend .
RUN npm run build

FROM node:20-alpine
WORKDIR /app
COPY --from=base /app .
ENV PORT=3000
EXPOSE 3000
CMD ["npm", "run", "start"]
